'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.18034
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GUIDosbox.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anglais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anglais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property assoc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("assoc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property attrib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("attrib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property batchtoexe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("batchtoexe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bateditor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bateditor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cacls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cacls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property chkdsk() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("chkdsk", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property cmd() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property cmd1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cmd1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property comp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("comp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property compact() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("compact", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property convert() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("convert", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property headerGUIDOSBOX() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("headerGUIDOSBOX", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property help() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Media_Player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Media_Player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Menu_EN_GuiDosBox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu_EN_GuiDosBox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Menu_GuiDosBox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu_GuiDosBox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;items&gt;
        '''  &lt;item&gt;
        '''    &lt;content&gt;
        '''      &lt;![CDATA[&lt;span class=&quot;title&quot;&gt;Tutoriel - GUI-DOSBOX&lt;/span&gt;
        ''' 
        ''' &lt;!--TITRE ET TEXTE ACCOMPAGNATEUR --&gt;
        '''&lt;p align=&quot;justify&quot;&gt;Tout dabord bienvenue dans &lt;span class=&quot;highlight&quot;&gt;GUI-DOSBOX&lt;/span&gt;&lt;/p&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;span class=&quot;highlight&quot;&gt;Ici, une mince description suivie de quelques petits conseils sur chaque application est disponible.&lt;/span&gt;&lt;/p&gt;
        '''&lt;p align=&quot;justify&quot;&gt;&lt;span class=&quot;subtitle&quot;&gt;Pour le fonctionnement du programme , la [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property page_1() As String
            Get
                Return ResourceManager.GetString("page_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;items&gt;
        '''  &lt;item&gt;
        '''    &lt;content&gt;
        '''      &lt;!--Coller page 1 et traduire à langlais ici.--&gt;
        '''    &lt;/content&gt;
        '''  &lt;/item&gt;
        '''&lt;/items&gt;.
        '''</summary>
        Friend ReadOnly Property page_10() As String
            Get
                Return ResourceManager.GetString("page_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;items&gt;
        '''  &lt;item&gt;
        '''    &lt;content&gt;
        '''      &lt;![CDATA[&lt;span class=&quot;title&quot;&gt;Aide&lt;/span&gt;
        '''  &lt;span class=&quot;subtitle&quot;&gt;Menu&lt;/span&gt;
        '''  &lt;p align=&quot;justify&quot;&gt;Sous l&apos;onglet &quot;Fichier&quot;, se trouve les options de langue, les langues disponibles sont le Français et l&apos;anglais. Toutes les applications lançables à l&apos;intérieur de GUIDosBox sont sous le volet &quot;Applications&quot;. Le volet &quot;Aide&quot; liste les applications et indique leur utilité.
        '''  &lt;span class=&quot;subtitle&quot;&gt;Applications&lt;/span&gt;
        '''  &lt;p align= [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property page_2() As String
            Get
                Return ResourceManager.GetString("page_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;items&gt;
        '''  &lt;item&gt;
        '''    &lt;content&gt;
        '''      &lt;![CDATA[&lt;span class=&quot;title&quot;&gt;Help&lt;/span&gt;
        '''  &lt;span class=&quot;subtitle&quot;&gt;Menus&lt;/span&gt;
        '''  &lt;p align=&quot;justify&quot;&gt;In the &quot;File&quot; menu, you may find the language options, available languages happen to be English or french at the momment. Every application launchable from GUIDosBox can be found in the &quot;Aplications&quot; menu. The &quot;Help&quot; menu lists evey application and their use.
        '''  &lt;span class=&quot;subtitle&quot;&gt;Applications&lt;/span&gt;
        '''  &lt;p align=&quot;justify&quot;&gt;An [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property page_20() As String
            Get
                Return ResourceManager.GetString("page_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;items&gt;
        '''
        '''  &lt;item&gt;
        '''    &lt;content&gt;&lt;![CDATA[&lt;span class=&quot;title&quot;&gt;GUI DosBox - Info&lt;/span&gt; ]]&gt;&lt;/content&gt;
        '''  &lt;/item&gt;
        '''
        '''  &lt;item&gt;
        '''    &lt;content&gt;
        '''      &lt;![CDATA[&lt;a href=&quot;http://www.fr.kobixxe.com/produits.php&quot; target=&quot;_parent&quot; class=&quot;subtitle&quot;&gt;kobixxe.com/produits&lt;/a&gt;
        '''&lt;p align=&quot;justify&quot;&gt; &lt;a href=&quot;http://www.kobixxe.com&quot; target=&quot;_parent&quot;&gt;Kobixxe Devlopers&lt;/a&gt; Est fier de présenter GUIDosBox,   &lt;/p&gt; 
        '''&lt;p align=&quot;right&quot;&gt; Copyright 2011&lt;/p&gt;
        '''&lt;p align=&quot;right&quot;&gt; tout droits réser [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property page_3() As String
            Get
                Return ResourceManager.GetString("page_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;items&gt;
        '''
        '''  &lt;item&gt;
        '''    &lt;content&gt;&lt;![CDATA[&lt;span class=&quot;title&quot;&gt;GUI DosBox - Info&lt;/span&gt; ]]&gt;&lt;/content&gt;
        '''  &lt;/item&gt;
        '''
        '''  &lt;item&gt;
        '''    &lt;content&gt;
        '''      &lt;![CDATA[&lt;a href=&quot;http://www.en.kobixxe.com/produits.php&quot; target=&quot;_parent&quot; class=&quot;subtitle&quot;&gt;kobixxe.com/produits&lt;/a&gt;
        '''&lt;p align=&quot;justify&quot;&gt; &lt;a href=&quot;http://www.kobixxe.com&quot; target=&quot;_parent&quot;&gt;Kobixxe Devlopers&lt;/a&gt; Is proud to present GUIDosBox,   &lt;/p&gt; 
        '''&lt;p align=&quot;right&quot;&gt; Copyright 2011&lt;/p&gt;
        '''&lt;p align=&quot;right&quot;&gt; all rights reserved [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property page_30() As String
            Get
                Return ResourceManager.GetString("page_30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property progressBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property progressBarBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressBarBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quebec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quebec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property rd() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("rd", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à p {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 20px;
        '''	color: #CCCCCC;
        '''}
        '''
        '''a {
        '''	color: #3399FF;
        '''	text-decoration: underline;
        '''}
        '''
        '''a:hover {
        '''	color: #CC6600;
        '''	text-decoration: none;
        '''}
        '''
        '''.title {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 32px;
        '''	color: #999999;
        '''}
        '''
        '''.subtitle {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 20px;
        '''	color: #CCCC66;
        '''}
        '''
        '''.highlight {
        '''	color: #99CC66;
        '''}
        '''
        '''.note {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 12p [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property style() As String
            Get
                Return ResourceManager.GetString("style", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à p {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 14px;
        '''	color: #CCCCCC;
        '''}
        '''
        '''a {
        '''	color: #3399FF;
        '''	text-decoration: underline;
        '''}
        '''
        '''a:hover {
        '''	color: #CC6600;
        '''	text-decoration: none;
        '''}
        '''
        '''.title {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 32px;
        '''	color: #999999;
        '''}
        '''
        '''.subtitle {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 20px;
        '''	color: #CCCC66;
        '''}
        '''
        '''.highlight {
        '''	color: #99CC66;
        '''}
        '''
        '''.note {
        '''	font-family: Arial, Helvetica, sans-serif;
        '''	font-size: 12p [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property style2() As String
            Get
                Return ResourceManager.GetString("style2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property subst() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("subst", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property system_info() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("system_info", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property tracert() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("tracert", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property type() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("type", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property where() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("where", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property whoami() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("whoami", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Writing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Writing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Friend ReadOnly Property xcopy() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xcopy", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Xion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
